### ISSUE TITLE
Checklist: JavaCC error/warning coverage

### ISSUE THREAD

**Issue by oowekyala** [oowekyala/intellij-javacc#12]
# Semantic errors
- [ ] 56 JavaCCErrors.semantic_error(this, "Invalid range : \"" + (int)l + "\" - \""
- [x] 368 JavaCCErrors.semantic_error(this, "Empty character set is not allowed as it will not match any character.");
- [ ] 81 JavaCCErrors.semantic_error(p, p.getLhs() + " occurs on the left hand side of more than one production.");
- [ ] 110 JavaCCErrors.semantic_error(res.nsTok, "Lexical state \"" + res.nextState +
- [ ] 117 JavaCCErrors.semantic_error(res.rexp, "EOF action/state change must be specified for all states, " + "i.e., <*>TOKEN:.
- [ ] 120 JavaCCErrors.semantic_error(res.rexp, "EOF action/state change can be specified only in a " + "TOKEN specification.
- [ ] 123 JavaCCErrors.semantic_error(res.rexp, "Duplicate action/state change specification for <EOF>.");
- [ ] 136 JavaCCErrors.semantic_error(res.rexp, "Private (#) regular expression cannot be defined within " + "grammar productions.
- [ ] 158 JavaCCErrors.semantic_error(res.rexp, "Multiply defined lexical token name \"" + s + "\".");
- [ ] 163 JavaCCErrors.semantic_error(res.rexp, "Lexical token name \"" + s + "\" is the same as " + "that of a lexical state.
- [ ] 217 JavaCCErrors.semantic_error(sl, "String \"" + sl.image + "\" can never be matched " + "due to presence of more general (IGNORE_CASE) regular expression " + "at line " + other.getLine() + ", column " + other.getColumn() + ".
- [ ] 222 JavaCCErrors.semantic_error(sl, "Duplicate definition of string token \"" + sl.image + "\" " + "can never be matched.
- [ ] 258 JavaCCErrors.semantic_error(sl, "Duplicate definition of string token \"" + sl.image + "\".");
- [ ] 260 JavaCCErrors.semantic_error(sl, "Duplicate definition of string token \"" + sl.image + " in lexical state \"" + tp.lexStates[i] + "\"."
- [ ] 264 JavaCCErrors.semantic_error(sl, "String token \"" + sl.image + "\" has been defined as a \"" + TokenProduction.kindImage[re.tpContext.kind] + "\" token."
- [ ] 267 JavaCCErrors.semantic_error(sl, "String token \"" + sl.image + "has been defined as a private regular expression."
- [ ] 444 JavaCCErrors.semantic_error(rexp, "Loop in regular expression detected: \"" + loopString + "\"");
- [ ] 572 JavaCCErrors.semantic_error(prod, "Left recursion detected: \"" + loopString + "\"");
- [ ] 583 JavaCCErrors.semantic_error(prod, "Left recursion detected: \"" + loopString + "\"");
- [ ] 614 JavaCCErrors.semantic_error(jn.regexpr, "Loop in regular expression detected: \"" + loopString + "\"");
- [ ] 668 JavaCCErrors.semantic_error(e, "Undefined lexical token name \"" + jn.label + "\".");
- [ ] 670 JavaCCErrors.semantic_error(e, "Token name \"" + jn.label + "\" refers to a private " + "(with a #) regular expression.
- [ ] 673 JavaCCErrors.semantic_error(e, "Token name \"" + jn.label + "\" refers to a non-token " + "(SKIP, MORE, IGNORE_IN_BNF) regular expression.
- [x] 757 JavaCCErrors.semantic_error(e, "Non-terminal " + nt.getName() + " has not been defined.");
- [x] 779 JavaCCErrors.semantic_error(e, "Expansion within \"(...)+\" can be matched by empty string.");
- [x] 783 JavaCCErrors.semantic_error(e, "Expansion within \"(...)*\" can be matched by empty string.");
- [x] 787 JavaCCErrors.semantic_error(e, "Expansion within \"(...)?\" can be matched by empty string.");

# Warnings

- [ ] JavaCCParserInternals.java  (2 usages found)
    - [ ] 110 JavaCCErrors.warning(p, "Ignoring lexical state specifications since option " +
    - [ ] 138 JavaCCErrors.warning(t, "Ignoring declarations in \"TOKEN_MGR_DECLS\" since option " +
- [ ] LexGen.java  (2 usages found)
    - [ ] 713 JavaCCErrors.warning(rexprs[initMatch[i]],
    - [ ] 721 JavaCCErrors.warning(rexprs[initMatch[i]],"Regular expression" + ((rexprs[initMatch[i]].label.equals(""))
                                                                          ? "" : (" for " + rexprs[initMatch[i]].label)) +
                                                                          " can be matched by the empty string (\"\") in lexical state " +
                                                                          lexStateName[i] + ". This regular expression along with the " +
                                                                          "regular expressions at " + reList + " forms the cycle \n   " +
                                                                          cycle + "\ncontaining regular expressions with empty matches." +
                                                                         " This can result in an endless loop of empty string matches.
- [ ] LookaheadCalc.java  (3 usages found)
    - [ ] 133 JavaCCErrors.warning(exp, "This choice can expand to the empty token sequence " +
    - [ ] 137 JavaCCErrors.warning(exp, "JAVACODE non-terminal will force this choice to be taken " +
    - [ ] 242 JavaCCErrors.warning(nested, "JAVACODE non-terminal within " + image(exp) +
- [ ] NfaState.java  (2 usages found)
    - [ ] 210 JavaCCErrors.warning(Main.lg.curRE, "Non-ASCII characters used in regular expression.\n" +
    - [ ] 254 JavaCCErrors.warning(Main.lg.curRE, "Non-ASCII characters used in regular expression.\n" +
- [ ] Options.java  (6 usages found)
    - [ ] 369 JavaCCErrors.warning(nameloc, "Bad option name \"" + name
    - [ ] 390 JavaCCErrors.warning(valueloc, "Bad option value \"" + value
    - [ ] 397 JavaCCErrors.warning(nameloc, "Duplicate option setting for \""
    - [ ] 404 JavaCCErrors.warning(nameloc, "Command line setting of \"" + name + "\" modifies option value in file.");
    - [ ] 418 JavaCCErrors.warning(valueloc, "Bad option value \"" + value
    - [ ] 431 JavaCCErrors.warning(valueloc, "Bad option value \"" + value
- [ ] OtherFilesGen.java  (1 usage found)
    - [ ] 166 JavaCCErrors.warning(re, "Consider giving this non-string token a label for better error reporting.");
- [ ] OtherFilesGenCPP.java  (1 usage found)
    - [ ] 141 JavaCCErrors.warning(re, "Consider giving this non-string token a label for better error reporting.");
- [ ] RChoice.java  (2 usages found)
    - [ ] 154 JavaCCErrors.warning(this, "Regular Expression choice  : " + curRE.label + " can never be matched as : " + label
    - [ ] 157 JavaCCErrors.warning(this, "Regular Expression choice : " + curRE.label + " can never be matched as token of kind : " + ordinal
- [ ] RStringLiteral.java  (1 usage found)
    - [ ] 331 JavaCCErrors.warning(Main.lg.curRE, "Non-ASCII characters used in regular expression." +
- [ ] Semanticize.java  (7 usages found)
    - [ ] 128 JavaCCErrors.warning(res.rexp, "Ignoring regular expression specification since " +
    - [ ] 131 JavaCCErrors.warning(res.rexp, "Ignoring free-standing regular expression reference.  " +
    - [ ] 236 JavaCCErrors.warning(sl, "String with IGNORE_CASE is partially superceded by string at" + pos + ".");
    - [ ] 238 JavaCCErrors.warning(sl, "String with IGNORE_CASE is partially superceded by strings at" + pos + ".");
    - [ ] 376 JavaCCErrors.warning(res.rexp, "Unlabeled regular expression cannot be referred to by " +
    - [ ] 721 JavaCCErrors.warning(la, "Encountered LOOKAHEAD(...) at a non-choice location.  " +
    - [ ] 724 JavaCCErrors.warning(la, "Encountered LOOKAHEAD(...) at a non-choice location.  This will be ignored.");
- [ ] JavaCCParser.java  (7 usages found)
    - [ ] 645 JavaCCErrors.warning(getToken(0), "Regular expression is being treated as if it were a TOKEN since option USER_TOKEN_MANAGER has been set to true.");
    - [ ] 654 JavaCCErrors.warning(t, "Ignoring \"IGNORE_CASE\" specification since option USER_TOKEN_MANAGER has been set to true.");
    - [ ] 741 JavaCCErrors.warning(t, "Ignoring action in regular expression specification since option USER_TOKEN_MANAGER has been set to true.");
    - [ ] 821 JavaCCErrors.warning(t, "Only semantic lookahead specifications within other lookahead specifications is considered.  Syntactic lookahead is ignored.");
    - [ ] 995 JavaCCErrors.warning(t, "Encountered LOOKAHEAD(...) at a non-choice location.  Only semantic lookahead will be considered here.");
    - [ ] 997 JavaCCErrors.warning(t, "Encountered LOOKAHEAD(...) at a non-choice location.  This will be ignored.");
    - [ ] 1011 JavaCCErrors.warning(t, "Action within lookahead specification will be ignored.");
